language: python
sudo: required
dist: xenial
python:
- 3.6
- 3.7
- 3.8
- 3.9
install:
- pip install -r requirements-dev.txt
- make compile
- make develop
script: py.test -vv
branches:
  only:
    - master
notifications:
  email:
    on_failure: always
    on_success: never
